[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# If your app itself needs SPA fallback on its own *.netlify.app:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
